apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-pods
  namespace: default
  labels:
    app: external-pods
spec:
  replicas: 3
  selector:
    matchLabels:
      app: external-pods
  template:
    metadata:
      labels:
        app: external-pods
    spec:
      containers:
      - name: with-resource
        image: registry.k8s.io/e2e-test-images/busybox:1.29-2
        command: ["sh", "-c", "ls -la /dev/dri/ && sleep 30"]
        resources:
          claims:
          - name: resource
      - name: without-resource
        image: registry.k8s.io/e2e-test-images/busybox:1.29-2
        command: ["sh", "-c", "ls -la /dev/ && sleep 30"]
      resourceClaims:
      - name: resource
        source:
          resourceClaimName: ext-gpu-claim
---
apiVersion: gpu.dra.intel.com/v1alpha
kind: GpuClaimParameters
metadata:
  name: ext-gpu-claim-params
spec:
  count: 1
  type: "gpu"
  memory: 256
---
apiVersion: resource.k8s.io/v1alpha1
kind: ResourceClaim
metadata:
  name: ext-gpu-claim
spec:
  resourceClassName: intel-gpu
  allocationMode: Immediate
  parametersRef:
    apiGroup: gpu.dra.intel.com/v1alpha
    kind: GpuClaimParameters
    name: ext-gpu-claim-params
